# Node
FROM node:23 AS builder

RUN mkdir app
WORKDIR app

COPY frontend/package.json frontend/package-lock.json .
RUN --mount=type=cache,target=/root/.npm npm ci

COPY frontend/src src
COPY frontend/public public

RUN yarn build && yarn cache clean

# Nginx
FROM nginx:1.17.6

COPY web/nginx-prod.conf /etc/nginx/nginx.conf
COPY --from=builder /app/build /app

EXPOSE 80/tcp
